### ISSUE TITLE
makefile still references old template files

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib-gamejam-template#2]
The makefile still has reference to 
```
    screen_logo.c \
    screen_title.c \
    screen_options.c \
    screen_gameplay.c \
    screen_ending.c
    
```
  But they are not used by the code nor included. They need to be removed for the makefile to work

**Comment by raysan5** [comment]
@JeffM2501 I reviewed the Makefile, actually it intended to be used through GitHub Actions and `PROJECT_SOURCE_FILES` were provided externally on the `make` call.
