### ISSUE TITLE
Suggestion: ignore the `src/*.aps` file

### ISSUE THREAD

**Issue by erikyuzwa** [raysan5/raylib-gamejam-template#5]
Awesome template and starting point which really helps out @raysan5! ❤️ 

Suggestion: When I open the project's RC file, VS generates a binary "helper" file `src/raylib_game.aps`.
I think that can be added to the `.gitignore`.

**Comment by raysan5** [comment]
@erikyuzwa Thanks for the improvement! Reviewed `.gitignore`!
